version: '3.8'

services:
  # Database Service
  metro-db:
    build:
      context: ./metro-db
    container_name: metro-db
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - metro-network

  # Backend Service
  metro-be:
    build:
      context: ./metro-be
      args:
        - MAVEN_OPTS=-Dmaven.repo.local=/maven-repo
    container_name: metro-be
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      metro-db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://metro-db:3306/metro?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: metro
      SPRING_DATASOURCE_PASSWORD: metro
    networks:
      - metro-network
    volumes:
      - maven-repo:/maven-repo

  # Frontend Service with Nginx
  metro-fe:
    build:
      context: ./metro-fe
      args:
        - NODE_OPTIONS=--max-old-space-size=1536
        - LOW_MEMORY=true
    container_name: metro-fe
    restart: always
    ports:
      - '3333:3333'
    depends_on:
      - metro-be
    volumes:
      - ./metro-fe/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - BACKEND_API_URL=http://metro-be:8080
    deploy:
      resources:
        limits:
          memory: 1.5G
          cpus: '1'
    networks:
      - metro-network

volumes:
  mysql-data:
    driver: local
  maven-repo:
    driver: local

networks:
  metro-network:
    driver: bridge
