version: '3.8'

services:
  # Database Service
  metro-db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=88888888
      - MYSQL_DATABASE=metro
      - MYSQL_USER=metro
      - MYSQL_PASSWORD=metro
    volumes:
      - mysql-data:/var/lib/mysql
      - ./metro-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  # Backend Service
  metro-be:
    build:
      context: ./metro-be
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - metro-db
    environment:
      SPRING_PROFILES_ACTIVE: docker
      MYSQL_USER: ${MYSQL_USER:-metro}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-metro}

  # Frontend Service with Development Server
  metro-fe:
    build:
      context: ./metro-fe
    restart: always
    ports:
      - '3333:3333'
    depends_on:
      - metro-be
    volumes:
      - ./metro-fe:/app
      - /app/node_modules

volumes:
  mysql-data:
