server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    # url: jdbc:mysql://8.130.172.82:3306/metro
    url: jdbc:mysql://39.101.76.177:3306/metro
    username: metro
    password: metro
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN
  main:
    allow-circular-references: true
