server:
  port: 8123
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://8.130.172.82:3306/demo
    username: root
    password: root888
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN
  main:
    allow-circular-references: true
